packages:
  - 'apps/*'
  - 'modules/demo/*'
  - 'modules/core/ts/*'
  - 'modules/watchlist/ts'
  - 'modules/watchlist/svelte'
  - 'modules/portfolio/ts'
  - 'modules/portfolio/svelte'
  - 'modules/demo/ts'
