packages:
  - "apps/*"
  - "modules/demo/ts"
  - "modules/demo/svelte"
  - "modules/watchlist/ts"
  - "modules/watchlist/svelte"
  - "modules/portfolio/ts"
  - "modules/portfolio/svelte"
  - "scripts/module-workflow"

onlyBuiltDependencies:
  - "virtual-module-core"
